# Generated by Django 4.1.3 on 2022-11-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
